name: flutter_native_splash_module
description: "JuneFlow Module for Flutter Native Splash"
#publish_to: 'none'
repository: https://github.com/juneflow-songdo/flutter_native_splash_module

version: 0.0.1+2

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0
  june_flow_util:
  flutter_native_splash: ^2.4.0 #@add

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

#@add start
flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/module/flutter_native_splash_module/background.png"
  image: assets/module/flutter_native_splash_module/splash_icon.png

  color_dark: "#ffffff"
  ##background_image_dark: "assets/module/flutter_native_splash_module/dark-background.png"
  image_dark: assets/module/flutter_native_splash_module/splash_icon.png

  #android: false
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  fullscreen: true
#@add end